//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETNHAPHANG
    {
        public string MASP { get; set; }
        public string MANPP { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<int> SL_NHAPHANG { get; set; }
        public Nullable<int> TONGGIATRI { get; set; }
        public Nullable<System.DateTime> NGAYNHAPHANG { get; set; }
        public bool TRANGTHAI { get; set; }
    
        public virtual NHAPHANPHOI NHAPHANPHOI { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI1 { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual SANPHAM SANPHAM1 { get; set; }
    }
}
