//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHOADONBANHANG
    {
        public string MAHD { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public string DVT { get; set; }
        public bool TRANGTHAI { get; set; }
    
        public virtual HOADONBANHANG HOADONBANHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
