//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTNHAPHANGTUNPP
    {
        public string MAHDNH { get; set; }
        public string MANPP { get; set; }
        public Nullable<decimal> TONGGIATRI { get; set; }
        public bool TRANGTHAI { get; set; }
    
        public virtual HOADONNHAPHANG HOADONNHAPHANG { get; set; }
        public virtual HOADONNHAPHANG HOADONNHAPHANG1 { get; set; }
        public virtual HOADONNHAPHANG HOADONNHAPHANG2 { get; set; }
        public virtual HOADONNHAPHANG HOADONNHAPHANG3 { get; set; }
        public virtual HOADONNHAPHANG HOADONNHAPHANG4 { get; set; }
        public virtual HOADONNHAPHANG HOADONNHAPHANG5 { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI1 { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI2 { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI3 { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI4 { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI5 { get; set; }
    }
}
