//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOIDONVINEN
    {
        public int ID { get; set; }
        public string TENGACH { get; set; }
        public string SOMETNEN { get; set; }
        public bool TRANGTHAI { get; set; }
    }
}
