//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBANHANG
    {
        public string MAHD { get; set; }
        public int MAKH { get; set; }
        public string NV_LAP_HD { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public bool TRANGTHAI { get; set; }
    }
}
