//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBANHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONBANHANG()
        {
            this.CONGNO = new HashSet<CONGNO>();
            this.CTHOADONBANHANG = new HashSet<CTHOADONBANHANG>();
        }
    
        public string MAHD { get; set; }
        public string MAKH { get; set; }
        public string NV_LAP_HD { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public bool TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGNO> CONGNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADONBANHANG> CTHOADONBANHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
