//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUHETHONG
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string NV_THAOTAC { get; set; }
        public string VITRI_THAOTAC { get; set; }
        public string GHICHU { get; set; }
    }
}
