//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADONBANHANG = new HashSet<HOADONBANHANG>();
            this.HOADONBANHANG1 = new HashSet<HOADONBANHANG>();
            this.HOADONBANHANG2 = new HashSet<HOADONBANHANG>();
            this.HOADONBANHANG3 = new HashSet<HOADONBANHANG>();
            this.HOADONBANHANG4 = new HashSet<HOADONBANHANG>();
            this.HOADONBANHANG5 = new HashSet<HOADONBANHANG>();
            this.HOADONNHAPHANG = new HashSet<HOADONNHAPHANG>();
            this.HOADONNHAPHANG1 = new HashSet<HOADONNHAPHANG>();
            this.HOADONNHAPHANG2 = new HashSet<HOADONNHAPHANG>();
            this.HOADONNHAPHANG3 = new HashSet<HOADONNHAPHANG>();
            this.HOADONNHAPHANG4 = new HashSet<HOADONNHAPHANG>();
            this.HOADONNHAPHANG5 = new HashSet<HOADONNHAPHANG>();
        }
    
        public string MANV { get; set; }
        public string MATKHAU { get; set; }
        public string TENNV { get; set; }
        public string SDT { get; set; }
        public Nullable<int> CMND { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> LUONGCB { get; set; }
        public string CHUCVU { get; set; }
        public string ANHDAIDIEN { get; set; }
        public bool TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBANHANG> HOADONBANHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBANHANG> HOADONBANHANG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBANHANG> HOADONBANHANG2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBANHANG> HOADONBANHANG3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBANHANG> HOADONBANHANG4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBANHANG> HOADONBANHANG5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONNHAPHANG> HOADONNHAPHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONNHAPHANG> HOADONNHAPHANG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONNHAPHANG> HOADONNHAPHANG2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONNHAPHANG> HOADONNHAPHANG3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONNHAPHANG> HOADONNHAPHANG4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONNHAPHANG> HOADONNHAPHANG5 { get; set; }
        public virtual QUYENHAN QUYENHAN { get; set; }
        public virtual QUYENHAN QUYENHAN1 { get; set; }
        public virtual QUYENHAN QUYENHAN2 { get; set; }
        public virtual QUYENHAN QUYENHAN3 { get; set; }
        public virtual QUYENHAN QUYENHAN4 { get; set; }
        public virtual QUYENHAN QUYENHAN5 { get; set; }
    }
}
