//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANPHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAPHANPHOI()
        {
            this.CTNHAPHANGTUNPP = new HashSet<CTNHAPHANGTUNPP>();
            this.CTNHAPHANGTUNPP1 = new HashSet<CTNHAPHANGTUNPP>();
            this.CTNHAPHANGTUNPP2 = new HashSet<CTNHAPHANGTUNPP>();
            this.CTNHAPHANGTUNPP3 = new HashSet<CTNHAPHANGTUNPP>();
            this.CTNHAPHANGTUNPP4 = new HashSet<CTNHAPHANGTUNPP>();
            this.CTNHAPHANGTUNPP5 = new HashSet<CTNHAPHANGTUNPP>();
            this.CHITIETNHAPHANG = new HashSet<CHITIETNHAPHANG>();
            this.CHITIETNHAPHANG1 = new HashSet<CHITIETNHAPHANG>();
            this.CHITIETNHAPHANG2 = new HashSet<CHITIETNHAPHANG>();
            this.CHITIETNHAPHANG3 = new HashSet<CHITIETNHAPHANG>();
            this.CHITIETNHAPHANG4 = new HashSet<CHITIETNHAPHANG>();
            this.CHITIETNHAPHANG5 = new HashSet<CHITIETNHAPHANG>();
            this.SANPHAM = new HashSet<SANPHAM>();
            this.SANPHAM1 = new HashSet<SANPHAM>();
            this.SANPHAM2 = new HashSet<SANPHAM>();
            this.SANPHAM3 = new HashSet<SANPHAM>();
            this.SANPHAM4 = new HashSet<SANPHAM>();
            this.SANPHAM5 = new HashSet<SANPHAM>();
        }
    
        public string MANPP { get; set; }
        public string TENNPP { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string WEBSITE { get; set; }
        public bool TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNHAPHANGTUNPP> CTNHAPHANGTUNPP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNHAPHANGTUNPP> CTNHAPHANGTUNPP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNHAPHANGTUNPP> CTNHAPHANGTUNPP2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNHAPHANGTUNPP> CTNHAPHANGTUNPP3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNHAPHANGTUNPP> CTNHAPHANGTUNPP4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNHAPHANGTUNPP> CTNHAPHANGTUNPP5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANG2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANG3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANG4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANG5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM5 { get; set; }
    }
}
