//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETNHAPHANGs = new HashSet<CHITIETNHAPHANG>();
            this.CTHOADONBANHANGs = new HashSet<CTHOADONBANHANG>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> GIABAN { get; set; }
        public Nullable<int> SL_TON { get; set; }
        public string MANPP { get; set; }
        public string MAANH { get; set; }
        public string MALOAI { get; set; }
        public bool TRANGTHAI { get; set; }
    
        public virtual ANHMINHHOASP ANHMINHHOASP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADONBANHANG> CTHOADONBANHANGs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHAPHANPHOI NHAPHANPHOI { get; set; }
    }
}
